/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupervisorRouteImport } from './routes/_authenticated/supervisor'
import { Route as AuthenticatedSeminovosRouteImport } from './routes/_authenticated/seminovos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPmpRouteImport } from './routes/_authenticated/pmp'
import { Route as AuthenticatedPcmRouteImport } from './routes/_authenticated/pcm'
import { Route as AuthenticatedMecanicoRouteImport } from './routes/_authenticated/mecanico'
import { Route as AuthenticatedFrotaRouteImport } from './routes/_authenticated/frota'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPlannerIndexRouteImport } from './routes/_authenticated/planner.index'
import { Route as AuthenticatedInspetorIndexRouteImport } from './routes/_authenticated/inspetor.index'
import { Route as AuthenticatedFrotaIndexRouteImport } from './routes/_authenticated/frota.index'
import { Route as AuthenticatedPlannerCalendarioRouteImport } from './routes/_authenticated/planner.calendario'
import { Route as AuthenticatedPlannerPrefixoRouteImport } from './routes/_authenticated/planner.$prefixo'
import { Route as AuthenticatedInspetorNovaRouteImport } from './routes/_authenticated/inspetor.nova'
import { Route as AuthenticatedInspetorIdRouteImport } from './routes/_authenticated/inspetor.$id'
import { Route as AuthenticatedFrotaCatalogoRouteImport } from './routes/_authenticated/frota.catalogo'
import { Route as AuthenticatedOsPreventivaIdRouteImport } from './routes/_authenticated/os.preventiva.$id'
import { Route as AuthenticatedOsCorretivaIdRouteImport } from './routes/_authenticated/os.corretiva.$id'

const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupervisorRoute = AuthenticatedSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeminovosRoute = AuthenticatedSeminovosRouteImport.update({
  id: '/seminovos',
  path: '/seminovos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPmpRoute = AuthenticatedPmpRouteImport.update({
  id: '/pmp',
  path: '/pmp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPcmRoute = AuthenticatedPcmRouteImport.update({
  id: '/pcm',
  path: '/pcm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMecanicoRoute = AuthenticatedMecanicoRouteImport.update({
  id: '/mecanico',
  path: '/mecanico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrotaRoute = AuthenticatedFrotaRouteImport.update({
  id: '/frota',
  path: '/frota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlannerIndexRoute =
  AuthenticatedPlannerIndexRouteImport.update({
    id: '/planner/',
    path: '/planner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspetorIndexRoute =
  AuthenticatedInspetorIndexRouteImport.update({
    id: '/inspetor/',
    path: '/inspetor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFrotaIndexRoute = AuthenticatedFrotaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedFrotaRoute,
} as any)
const AuthenticatedPlannerCalendarioRoute =
  AuthenticatedPlannerCalendarioRouteImport.update({
    id: '/planner/calendario',
    path: '/planner/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlannerPrefixoRoute =
  AuthenticatedPlannerPrefixoRouteImport.update({
    id: '/planner/$prefixo',
    path: '/planner/$prefixo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspetorNovaRoute =
  AuthenticatedInspetorNovaRouteImport.update({
    id: '/inspetor/nova',
    path: '/inspetor/nova',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInspetorIdRoute = AuthenticatedInspetorIdRouteImport.update({
  id: '/inspetor/$id',
  path: '/inspetor/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFrotaCatalogoRoute =
  AuthenticatedFrotaCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => AuthenticatedFrotaRoute,
  } as any)
const AuthenticatedOsPreventivaIdRoute =
  AuthenticatedOsPreventivaIdRouteImport.update({
    id: '/os/preventiva/$id',
    path: '/os/preventiva/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOsCorretivaIdRoute =
  AuthenticatedOsCorretivaIdRouteImport.update({
    id: '/os/corretiva/$id',
    path: '/os/corretiva/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/frota': typeof AuthenticatedFrotaRouteWithChildren
  '/mecanico': typeof AuthenticatedMecanicoRoute
  '/pcm': typeof AuthenticatedPcmRoute
  '/pmp': typeof AuthenticatedPmpRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/seminovos': typeof AuthenticatedSeminovosRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/frota/catalogo': typeof AuthenticatedFrotaCatalogoRoute
  '/inspetor/$id': typeof AuthenticatedInspetorIdRoute
  '/inspetor/nova': typeof AuthenticatedInspetorNovaRoute
  '/planner/$prefixo': typeof AuthenticatedPlannerPrefixoRoute
  '/planner/calendario': typeof AuthenticatedPlannerCalendarioRoute
  '/frota/': typeof AuthenticatedFrotaIndexRoute
  '/inspetor/': typeof AuthenticatedInspetorIndexRoute
  '/planner/': typeof AuthenticatedPlannerIndexRoute
  '/os/corretiva/$id': typeof AuthenticatedOsCorretivaIdRoute
  '/os/preventiva/$id': typeof AuthenticatedOsPreventivaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/mecanico': typeof AuthenticatedMecanicoRoute
  '/pcm': typeof AuthenticatedPcmRoute
  '/pmp': typeof AuthenticatedPmpRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/seminovos': typeof AuthenticatedSeminovosRoute
  '/supervisor': typeof AuthenticatedSupervisorRoute
  '/frota/catalogo': typeof AuthenticatedFrotaCatalogoRoute
  '/inspetor/$id': typeof AuthenticatedInspetorIdRoute
  '/inspetor/nova': typeof AuthenticatedInspetorNovaRoute
  '/planner/$prefixo': typeof AuthenticatedPlannerPrefixoRoute
  '/planner/calendario': typeof AuthenticatedPlannerCalendarioRoute
  '/frota': typeof AuthenticatedFrotaIndexRoute
  '/inspetor': typeof AuthenticatedInspetorIndexRoute
  '/planner': typeof AuthenticatedPlannerIndexRoute
  '/os/corretiva/$id': typeof AuthenticatedOsCorretivaIdRoute
  '/os/preventiva/$id': typeof AuthenticatedOsPreventivaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/frota': typeof AuthenticatedFrotaRouteWithChildren
  '/_authenticated/mecanico': typeof AuthenticatedMecanicoRoute
  '/_authenticated/pcm': typeof AuthenticatedPcmRoute
  '/_authenticated/pmp': typeof AuthenticatedPmpRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/seminovos': typeof AuthenticatedSeminovosRoute
  '/_authenticated/supervisor': typeof AuthenticatedSupervisorRoute
  '/_authenticated/frota/catalogo': typeof AuthenticatedFrotaCatalogoRoute
  '/_authenticated/inspetor/$id': typeof AuthenticatedInspetorIdRoute
  '/_authenticated/inspetor/nova': typeof AuthenticatedInspetorNovaRoute
  '/_authenticated/planner/$prefixo': typeof AuthenticatedPlannerPrefixoRoute
  '/_authenticated/planner/calendario': typeof AuthenticatedPlannerCalendarioRoute
  '/_authenticated/frota/': typeof AuthenticatedFrotaIndexRoute
  '/_authenticated/inspetor/': typeof AuthenticatedInspetorIndexRoute
  '/_authenticated/planner/': typeof AuthenticatedPlannerIndexRoute
  '/_authenticated/os/corretiva/$id': typeof AuthenticatedOsCorretivaIdRoute
  '/_authenticated/os/preventiva/$id': typeof AuthenticatedOsPreventivaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/trocar-senha'
    | '/admin'
    | '/dashboard'
    | '/frota'
    | '/mecanico'
    | '/pcm'
    | '/pmp'
    | '/relatorios'
    | '/seminovos'
    | '/supervisor'
    | '/frota/catalogo'
    | '/inspetor/$id'
    | '/inspetor/nova'
    | '/planner/$prefixo'
    | '/planner/calendario'
    | '/frota/'
    | '/inspetor/'
    | '/planner/'
    | '/os/corretiva/$id'
    | '/os/preventiva/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/trocar-senha'
    | '/admin'
    | '/dashboard'
    | '/mecanico'
    | '/pcm'
    | '/pmp'
    | '/relatorios'
    | '/seminovos'
    | '/supervisor'
    | '/frota/catalogo'
    | '/inspetor/$id'
    | '/inspetor/nova'
    | '/planner/$prefixo'
    | '/planner/calendario'
    | '/frota'
    | '/inspetor'
    | '/planner'
    | '/os/corretiva/$id'
    | '/os/preventiva/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/trocar-senha'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/frota'
    | '/_authenticated/mecanico'
    | '/_authenticated/pcm'
    | '/_authenticated/pmp'
    | '/_authenticated/relatorios'
    | '/_authenticated/seminovos'
    | '/_authenticated/supervisor'
    | '/_authenticated/frota/catalogo'
    | '/_authenticated/inspetor/$id'
    | '/_authenticated/inspetor/nova'
    | '/_authenticated/planner/$prefixo'
    | '/_authenticated/planner/calendario'
    | '/_authenticated/frota/'
    | '/_authenticated/inspetor/'
    | '/_authenticated/planner/'
    | '/_authenticated/os/corretiva/$id'
    | '/_authenticated/os/preventiva/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstalarRoute: typeof InstalarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/supervisor': {
      id: '/_authenticated/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof AuthenticatedSupervisorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seminovos': {
      id: '/_authenticated/seminovos'
      path: '/seminovos'
      fullPath: '/seminovos'
      preLoaderRoute: typeof AuthenticatedSeminovosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pmp': {
      id: '/_authenticated/pmp'
      path: '/pmp'
      fullPath: '/pmp'
      preLoaderRoute: typeof AuthenticatedPmpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pcm': {
      id: '/_authenticated/pcm'
      path: '/pcm'
      fullPath: '/pcm'
      preLoaderRoute: typeof AuthenticatedPcmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mecanico': {
      id: '/_authenticated/mecanico'
      path: '/mecanico'
      fullPath: '/mecanico'
      preLoaderRoute: typeof AuthenticatedMecanicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frota': {
      id: '/_authenticated/frota'
      path: '/frota'
      fullPath: '/frota'
      preLoaderRoute: typeof AuthenticatedFrotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/': {
      id: '/_authenticated/planner/'
      path: '/planner'
      fullPath: '/planner/'
      preLoaderRoute: typeof AuthenticatedPlannerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspetor/': {
      id: '/_authenticated/inspetor/'
      path: '/inspetor'
      fullPath: '/inspetor/'
      preLoaderRoute: typeof AuthenticatedInspetorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frota/': {
      id: '/_authenticated/frota/'
      path: '/'
      fullPath: '/frota/'
      preLoaderRoute: typeof AuthenticatedFrotaIndexRouteImport
      parentRoute: typeof AuthenticatedFrotaRoute
    }
    '/_authenticated/planner/calendario': {
      id: '/_authenticated/planner/calendario'
      path: '/planner/calendario'
      fullPath: '/planner/calendario'
      preLoaderRoute: typeof AuthenticatedPlannerCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planner/$prefixo': {
      id: '/_authenticated/planner/$prefixo'
      path: '/planner/$prefixo'
      fullPath: '/planner/$prefixo'
      preLoaderRoute: typeof AuthenticatedPlannerPrefixoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspetor/nova': {
      id: '/_authenticated/inspetor/nova'
      path: '/inspetor/nova'
      fullPath: '/inspetor/nova'
      preLoaderRoute: typeof AuthenticatedInspetorNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inspetor/$id': {
      id: '/_authenticated/inspetor/$id'
      path: '/inspetor/$id'
      fullPath: '/inspetor/$id'
      preLoaderRoute: typeof AuthenticatedInspetorIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/frota/catalogo': {
      id: '/_authenticated/frota/catalogo'
      path: '/catalogo'
      fullPath: '/frota/catalogo'
      preLoaderRoute: typeof AuthenticatedFrotaCatalogoRouteImport
      parentRoute: typeof AuthenticatedFrotaRoute
    }
    '/_authenticated/os/preventiva/$id': {
      id: '/_authenticated/os/preventiva/$id'
      path: '/os/preventiva/$id'
      fullPath: '/os/preventiva/$id'
      preLoaderRoute: typeof AuthenticatedOsPreventivaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/os/corretiva/$id': {
      id: '/_authenticated/os/corretiva/$id'
      path: '/os/corretiva/$id'
      fullPath: '/os/corretiva/$id'
      preLoaderRoute: typeof AuthenticatedOsCorretivaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedFrotaRouteChildren {
  AuthenticatedFrotaCatalogoRoute: typeof AuthenticatedFrotaCatalogoRoute
  AuthenticatedFrotaIndexRoute: typeof AuthenticatedFrotaIndexRoute
}

const AuthenticatedFrotaRouteChildren: AuthenticatedFrotaRouteChildren = {
  AuthenticatedFrotaCatalogoRoute: AuthenticatedFrotaCatalogoRoute,
  AuthenticatedFrotaIndexRoute: AuthenticatedFrotaIndexRoute,
}

const AuthenticatedFrotaRouteWithChildren =
  AuthenticatedFrotaRoute._addFileChildren(AuthenticatedFrotaRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFrotaRoute: typeof AuthenticatedFrotaRouteWithChildren
  AuthenticatedMecanicoRoute: typeof AuthenticatedMecanicoRoute
  AuthenticatedPcmRoute: typeof AuthenticatedPcmRoute
  AuthenticatedPmpRoute: typeof AuthenticatedPmpRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSeminovosRoute: typeof AuthenticatedSeminovosRoute
  AuthenticatedSupervisorRoute: typeof AuthenticatedSupervisorRoute
  AuthenticatedInspetorIdRoute: typeof AuthenticatedInspetorIdRoute
  AuthenticatedInspetorNovaRoute: typeof AuthenticatedInspetorNovaRoute
  AuthenticatedPlannerPrefixoRoute: typeof AuthenticatedPlannerPrefixoRoute
  AuthenticatedPlannerCalendarioRoute: typeof AuthenticatedPlannerCalendarioRoute
  AuthenticatedInspetorIndexRoute: typeof AuthenticatedInspetorIndexRoute
  AuthenticatedPlannerIndexRoute: typeof AuthenticatedPlannerIndexRoute
  AuthenticatedOsCorretivaIdRoute: typeof AuthenticatedOsCorretivaIdRoute
  AuthenticatedOsPreventivaIdRoute: typeof AuthenticatedOsPreventivaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFrotaRoute: AuthenticatedFrotaRouteWithChildren,
  AuthenticatedMecanicoRoute: AuthenticatedMecanicoRoute,
  AuthenticatedPcmRoute: AuthenticatedPcmRoute,
  AuthenticatedPmpRoute: AuthenticatedPmpRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSeminovosRoute: AuthenticatedSeminovosRoute,
  AuthenticatedSupervisorRoute: AuthenticatedSupervisorRoute,
  AuthenticatedInspetorIdRoute: AuthenticatedInspetorIdRoute,
  AuthenticatedInspetorNovaRoute: AuthenticatedInspetorNovaRoute,
  AuthenticatedPlannerPrefixoRoute: AuthenticatedPlannerPrefixoRoute,
  AuthenticatedPlannerCalendarioRoute: AuthenticatedPlannerCalendarioRoute,
  AuthenticatedInspetorIndexRoute: AuthenticatedInspetorIndexRoute,
  AuthenticatedPlannerIndexRoute: AuthenticatedPlannerIndexRoute,
  AuthenticatedOsCorretivaIdRoute: AuthenticatedOsCorretivaIdRoute,
  AuthenticatedOsPreventivaIdRoute: AuthenticatedOsPreventivaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InstalarRoute: InstalarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
